name: Node CI

on:
  push:
    branches: 
      - master
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Checkout project
      uses: actions/checkout@v1
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci
      env:
        CI: true

    - name: Build project
      run: npm run build

    - name: Test for Node.js
      run: npm run test-build-node

    - name: Test for browser
      run: npm run test-build-browser
