name: Unit Tests

on:
  push:
    branches: 
      - master
    
jobs:
  build-and-test:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Check out project
      uses: actions/checkout@v1
      
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci
      env:
        CI: true

    - name: Build project
      run: npm run build

    - name: Run tests for Node.js
      run: npm run test-build-node

    - name: Run test for browser
      run: npm run test-build-browser
